window.SITE={liveFeeds:[{name:"Match Centre",url:"https://rss.app/feeds/t3Lo9AUA1MlJkBVZ.xml"},{name:"World Cup Articles",url:"https://rss.app/feeds/6nYSUcj7Y38wSnoC.xml"},{name:"Football Headlines",url:"https://feeds.bbci.co.uk/sport/football/rss.xml"}]};
window.players=[{name:"Kylian Mbappé",country:"France",role:"Forward",meter:94,strengths:["Explosive pace","Clinical finishing","1v1 threat","Big-game experience"],weaknesses:["Defensive workload","Can be isolated against deep blocks"]},{name:"Jude Bellingham",country:"England",role:"Midfielder",meter:91,strengths:["Leadership","Late runs into the box","Ball carrying","Press resistance"],weaknesses:["Aggressive duels can bring cards","Heavy workload risk"]},{name:"Vinícius Júnior",country:"Brazil",role:"Winger",meter:90,strengths:["Dribbling","Acceleration","Chance creation","Counter attacks"],weaknesses:["Can be targeted physically","Finishing pressure in tight games"]},{name:"Jamal Musiala",country:"Germany",role:"Attacking Midfielder",meter:87,strengths:["Close control","Creativity","Composure","Movement between lines"],weaknesses:["Physical duels","Needs consistent end product"]}];
window.teams=[{team:"France",meter:94,strengths:["Squad depth","Pace in attack","Physical power"],weaknesses:["Pressure as favorites","Midfield balance debate"],needs:["Consistent finishing","Defensive focus"]},{team:"Argentina",meter:92,strengths:["Tournament mentality","Compact structure","Creative forwards"],weaknesses:["Aging core questions","Transition defending"],needs:["Fresh legs","Set-piece security"]},{team:"Brazil",meter:90,strengths:["Wide attackers","Individual flair","Fan support"],weaknesses:["Knockout pressure","Midfield stability"],needs:["Control in big games","Clinical finishing"]},{team:"England",meter:88,strengths:["Midfield talent","Set pieces","Premier League depth"],weaknesses:["Big-match pressure","System selection debate"],needs:["Balanced XI","Composure"]}];
window.goldenBoot=[{name:"Kylian Mbappé",country:"France",chance:94,reason:"Elite pace, penalty-box movement and proven tournament scoring record."},{name:"Vinícius Júnior",country:"Brazil",chance:88,reason:"Direct winger with huge chance creation and counter-attacking impact."},{name:"Jude Bellingham",country:"England",chance:82,reason:"Midfield runner who arrives in the box and can influence big moments."},{name:"Harry Kane",country:"England",chance:79,reason:"Penalty quality, link-up play and consistent finishing profile."}];
window.matchCenter=[{league:"World Cup 2026",home:"Mexico",away:"Opening Match",status:"June 11",score:"Kickoff",note:"The expanded tournament starts in North America with 48 teams."},{league:"World Cup 2026",home:"USA",away:"Canada",status:"Hosts",score:"16 Cities",note:"The event spans stadiums in the United States, Canada and Mexico."},{league:"World Cup 2026",home:"Knockouts",away:"Final",status:"Roadmap",score:"104 Games",note:"More matches, more stories and more ranking opportunities for fans."}];
window.blogs=[{title:"2026 World Cup Favorites: Teams to Watch",url:"world-cup-2026-favorites.html",desc:"Teams fans expect to challenge for the trophy."},{title:"World Cup 2026 Dark Horses",url:"world-cup-2026-dark-horses.html",desc:"Rising teams that could surprise bigger nations."},{title:"Golden Boot Race: Early Watchlist",url:"golden-boot-race-watchlist.html",desc:"Attackers who could compete for the top scorer award."},{title:"Host Cities Guide for Fans",url:"host-cities-fan-guide.html",desc:"Fan guide to the cities hosting the tournament."},{title:"Common World Cup Debates",url:"world-cup-controversies.html",desc:"VAR, squad selection, workload and fan debate topics."},{title:"Player Strengths & Weaknesses Guide",url:"player-analysis-guide.html",desc:"How to understand player profiles before major matches."}];
window.fallbackNews=[{title:"World Cup 2026 build-up continues across USA, Canada and Mexico",source:"World Cup Desk",date:"Updated today",link:"world-cup-2026.html",desc:"Tournament preparation, host city stories and fan interest before June 2026."},{title:"Fans debate early favorites for World Cup 2026",source:"Fan Analysis",date:"Updated today",link:"predictions.html",desc:"France, Argentina, Brazil and England remain major discussion points."},{title:"Golden Boot race watchlist gains attention",source:"Player Watch",date:"Updated today",link:"golden-boot.html",desc:"Star attackers are already part of fan predictions for top scorer race."}];
document.addEventListener("DOMContentLoaded",()=>{const m=document.querySelector(".menu"),h=document.querySelector(".hamb");if(h&&m)h.onclick=()=>m.classList.toggle("open");document.querySelectorAll("[data-year]").forEach(e=>e.textContent=new Date().getFullYear());setActiveNav();renderMatchCenter();renderPlayers();renderTeams();renderGoldenBoot();renderBlogs();loadLiveNews();});
function setActiveNav(){const current=(location.pathname.split('/').pop()||'index.html');document.querySelectorAll('.menu a').forEach(a=>{const href=a.getAttribute('href');a.classList.toggle('active',href===current || (current.includes('world-cup')&&href==='world-cup-2026.html'))})}
async function loadLiveNews(){const el=document.querySelector("#liveNews");if(!el)return;el.innerHTML='<article class="card"><span class="badge">Live Feed</span><h3>Loading latest updates...</h3><p>Fresh football stories will appear here. Fallback stories load automatically if RSS is blocked.</p></article>';let all=[];for(const feed of (SITE.liveFeeds||[])){try{const api="https://api.allorigins.win/raw?url="+encodeURIComponent(feed.url);const r=await fetch(api,{cache:"no-store"});if(!r.ok)continue;const txt=await r.text();const xml=new DOMParser().parseFromString(txt,"text/xml");const items=[...xml.querySelectorAll("item")].slice(0,4).map(item=>({title:item.querySelector("title")?.textContent||"Football update",link:item.querySelector("link")?.textContent||"#",date:item.querySelector("pubDate")?.textContent||"Recent",source:feed.name,desc:(item.querySelector("description")?.textContent||"").replace(/<[^>]+>/g,"").slice(0,180)}));all.push(...items)}catch(e){}}
if(!all.length)all=window.fallbackNews;el.innerHTML=all.slice(0,9).map(n=>`<article class="card"><span class="badge">${esc(n.source)}</span><h3>${esc(n.title)}</h3><time>${esc(n.date)}</time><p>${esc(n.desc)}</p><div class="actions"><a class="btn primary" href="${n.link}" target="${String(n.link).startsWith('http')?'_blank':'_self'}" rel="noopener">Read More</a><button class="btn secondary" onclick="sharePage('${attr(n.title)}')">Share</button></div></article>`).join("")}
function renderMatchCenter(){const el=document.querySelector("#matchCenter");if(!el)return;el.innerHTML=matchCenter.map(m=>`<article class="score-card"><div class="score-top"><span>${m.league}</span><b>${m.status}</b></div><div class="teams"><strong>${m.home}</strong><em>${m.score}</em><strong>${m.away}</strong></div><p>${m.note}</p></article>`).join("")}
function renderPlayers(){const el=document.querySelector("#playerGrid");if(!el)return;el.innerHTML=players.map(p=>`<article class="card"><span class="badge">${p.country} • ${p.role}</span><h3>${p.name}</h3><div class="meter"><span style="width:${p.meter}%"></span></div><div class="analysis"><div class="panel good"><h4>Strengths</h4><ul>${p.strengths.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="panel bad"><h4>Weaknesses</h4><ul>${p.weaknesses.map(x=>`<li>${x}</li>`).join("")}</ul></div></div></article>`).join("")}
function renderTeams(){const el=document.querySelector("#teamGrid");if(!el)return;el.innerHTML=teams.map(t=>`<article class="card"><span class="badge">Power Index ${t.meter}%</span><h3>${t.team}</h3><div class="meter"><span style="width:${t.meter}%"></span></div><div class="analysis"><div class="panel good"><h4>Strengths</h4><ul>${t.strengths.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="panel bad"><h4>Weaknesses</h4><ul>${t.weaknesses.map(x=>`<li>${x}</li>`).join("")}</ul></div></div><p><b>Needs:</b> ${t.needs.join(", ")}</p></article>`).join("")}
function renderGoldenBoot(){const el=document.querySelector("#goldenBootGrid");if(!el)return;el.innerHTML=goldenBoot.map((p,i)=>`<article class="card"><span class="badge">#${i+1} • ${p.country}</span><h3>${p.name}</h3><div class="meter"><span style="width:${p.chance}%"></span></div><p>${p.reason}</p></article>`).join("")}
function renderBlogs(){const el=document.querySelector("#blogGrid");if(!el)return;el.innerHTML=blogs.map(b=>`<a class="card" href="${b.url}"><span class="badge">Feature</span><h3>${b.title}</h3><p>${b.desc}</p><p><b>Read story →</b></p></a>`).join("")}
function siteSearch(){const q=(document.querySelector("#siteSearchInput")?.value||"world cup").toLowerCase();const box=document.querySelector("#searchResults");if(!box)return;const items=[["Latest Updates","news.html","Fresh football stories and RSS-style updates"],["Golden Boot","golden-boot.html","Top scorer race and player watchlist"],["Players","players.html","Player strengths and weaknesses"],["Teams","teams.html","Team power ranking and tactical notes"],["Predictions","predictions.html","Favorites and dark horses"],["World Cup Guide","world-cup-2026.html","Tournament format, dates and host guide"]];box.innerHTML=items.filter(x=>(x[0]+x[2]).toLowerCase().includes(q)||q.length<2||q.includes('world')||q.includes('cup')).map(x=>`<a class="card" href="${x[1]}"><span class="badge">Result</span><h3>${x[0]}</h3><p>${x[2]}</p></a>`).join("") || '<article class="card"><h3>No result found</h3><p>Try: team, player, Golden Boot, predictions or World Cup.</p></article>'}
function sharePage(text){const url=location.href;if(navigator.share)navigator.share({title:text,text,url});else if(navigator.clipboard){navigator.clipboard.writeText(url);alert("Link copied")}}
function esc(s){return String(s||"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}function attr(s){return String(s||"").replace(/['"]/g,"")}


// Mobile menu reliability and button click helpers
(function(){
  document.addEventListener('click', function(e){
    const menu=document.querySelector('.menu');
    const hamb=document.querySelector('.hamb');
    if(!menu||!hamb) return;
    if(e.target.closest('.hamb')){
      menu.classList.toggle('open');
      hamb.setAttribute('aria-expanded', menu.classList.contains('open') ? 'true':'false');
      e.stopPropagation();
      return;
    }
    if(e.target.closest('.menu a')){
      menu.classList.remove('open');
      hamb.setAttribute('aria-expanded','false');
      return;
    }
    if(menu.classList.contains('open') && !e.target.closest('.menu')){
      menu.classList.remove('open');
      hamb.setAttribute('aria-expanded','false');
    }
  }, true);
})();
